version: "3.8"
services:
  mail-server:
    build:
      context: .
      dockerfile: mailserver.Dockerfile
    expose:
      - 1080
      - 1025
    ports:
      - 1025:1025/tcp
      - 1080:1080/tcp


  pqe-rpc-server:
    image: pqe-rpc-server:latest
    ports:
      - 443:443/tcp
    environment:
      - SERVICE_NAME=pqe-rpc-server
      - SMTP_HOST=mail-server
      - SMTP_PORT=1025
      - SMTP_SSL=false
      - SMTP_USER=
      - SMTP_PASS=
    volumes:
      - ./shared-volume/ca:/ca-certs/
    depends_on:
      - mail-server

  openssl-pqe-applicant:
    build:
      context: .
      dockerfile: applicant.Dockerfile
    environment:
      - SERVER_HOST=pqe-rpc-server
    volumes:
      - ./shared-volume/ca:/ca-certs/
      - ./shared-volume/:/out
    ports:
      - 8081:8080/tcp
    command: ["./run.sh"]
    depends_on:
      - pqe-rpc-server


  openssl-pqe-ca:
    build:
      context: .
      dockerfile: ca.Dockerfile
    environment:
      - SERVER_HOST=pqe-rpc-server
      - ETHR_REGISTRY=0x488C83c4D1dDCF8f3696273eCcf0Ff4Cf54Bf277
      - DNS_REGISTRY=0x87570d1Be0174a214465E27D70647a564CaB595c
      - DNS_ADMIN_ADDRESS=0xa05ED7ab29f246aDa5f0eb76Bdf9A2F2558da63f
      - DNS_ADMIN_PRIVATE_KEY=946e789ceb2c1afba38b91e176fc4bb1a11b74f748bd9b7f0850d8977ac74a06
      - WEB3_RPC=https://writer.lacchain.net
      - NETWORK_ID=648529
    volumes:
      - ./shared-volume/ca:/ca-certs/
      - ./shared-volume/:/out
    ports:
      - 8082:8080/tcp
    command: ["./run.sh"]
    depends_on:
      - pqe-rpc-server


volumes:
  shared-volume:
